blank_issues_enabled: false
contact_links:
  - name: Home Assistant Community Forum
    url: https://community.home-assistant.io/t/samsung-multiroom-speakers/844722
    about: Please ask and answer questions here.